# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-23 21:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 23, 21, 45, 45, 840250)),
        ),
    ]
